### ISSUE TITLE
actionPerformed GUIEvent issue

### ISSUE THREAD

**Issue by jzeilmeier** [brendanberg/interfascia#13]
When testing the [actionPerformed example](http://interfascia.berg.industries/documentation/actionperformed) as is, all is OK. But adding the two print lines from the [GUIEvent example](http://interfascia.berg.industries/documentation/guievent) at the top of the method gives this error: 

> The type GUIComponent is not visible.

How can I solve this problem?

Here is the complete code:
```
import interfascia.*;

GUIController c;
IFButton b1, b2;

void setup() {
  c = new GUIController (this);
  
  b1 = new IFButton ("One", 30, 20, 40, 17);
  b2 = new IFButton ("Two", 30, 60, 40, 17);

  b1.addActionListener(this);
  b2.addActionListener(this);

  c.add (b1);
  c.add (b2);
}

void draw() {
}

void actionPerformed (GUIEvent e) {
  print ("Component: " + e.getSource().getLabel());
  print ("Message: " + e.getMessage());
  if (e.getSource() == b1) {
    println("Button one was clicked");
  } else if (e.getSource() == b2) {
    println("Button two was clicked");
  }
}
```

**Comment by brendanberg** [comment]
Hi, it looks like your issue has to do with the line `print ("Component: " + e.getSource().getLabel());`. I'm not entirely sure what is causing the problem, but a workaround is to cast the event source to an `IFButton` before getting the label:

```
void actionPerformed (GUIEvent e) {
    println("Component: " + ((IFButton) e.getSource()).getLabel());
    println("Message: " + e.getMessage());
    if (e.getSource() == b1) {
        println("Button one was clicked");
    } else if (e.getSource() == b2) {
        println("Button two was clicked");
    }
}
```

**Comment by brendanberg** [comment]
This seems to be related to issue #1, so I'll be looking into the changes recommended there.
