### ISSUE TITLE
interfascia 004 download, virus detected by McAfee 10/4/17

### ISSUE THREAD

**Issue by gpcwoodwk** [brendanberg/interfascia#16]
Tried to download the library for interfascia but encountered a virus detect so was deleted by McAfee.

**Comment by brendanberg** [comment]
Could you please tell me what operating system and version of McAfee you were using? A screen shot of whatever dialog box McAfee presented would also be helpful.

**Comment by gpcwoodwk** [comment]
Thanks Brendan for responding to my post.  I am running Window10 at the 
latest release.  I have attached a screen shot of the report from mcAfee 
when I try to download the interfascia library.  The browser is 
"Internet Explorer".   The McAfee app is up to date to the latest 
profiles:  Versions: Security Center 16.0.3, Virus Scan 20.3.  Hope this 
helps.
Thanks again
Mr. Gail Cone

**Comment by gpcwoodwk** [comment]
Hi Brendan

By any chance have you made progress on the download virus issue.
Thanks
Gail

**Comment by brendanberg** [comment]
I'm fairly certain this is a false alarm from McAfee. I've uploaded the file to an online multi-tool scanner and no viruses were detected.

https://www.virustotal.com/#/file/4ef866074ee0f46b1a452e9fe1f568b6636fd1562f58bcd3d6239086015a3956/detection
https://www.virustotal.com/#/file/e30ca5fcc37703aef00ec66c428245d48b3d47583f943f39ba259995e5800c9b/detection

**Comment by gpcwoodwk** [comment]
Thanks Brendan.
I seem to be running into this issue with false virus detection on a couple of things.  Windows 10 security flagged an application I tried to load a couple weeks ago.  This application download was also validated as being clean.  
Thank you for looking into this for me.  I will go ahead and download the GUI library.   Looking forward to giving it a try….
