### ISSUE TITLE
install

### ISSUE THREAD

**Issue by kaihansen79** [brendanberg/interfascia#2]
I've placed the library inside of  sketchbook>libraries, but when I run the FioXBeeConfigTool it cannot find interfascia.  Is this library compatable with Processing 1.5.1?

**Comment by brendanberg** [comment]
I'm not familiar with the FioXBeeConfigTool. The library should be compatible with the current version of Processing, but I will look into this particular case.

**Comment by brendanberg** [comment]
I'm working on a Processing 3.0-compatible update. Given the changes required, Interfascia won't be supporting versions of processing before 3.0.
